networks:
  mern-network:
    driver: bridge

services:

  # client service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8880:80"
    environment:
      - VITE_API_URL=http://api.yourdomain.com
    depends_on:
      - server
    networks:
      - mern-network

  # server service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5550:5000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - NODE_ENV=production
    depends_on:
      - mongodb
    networks:
      - mern-network

  # mongo service
  mongodb:
    image: mongo:latest
    ports:
      - "27099:27017"
    volumes:
      - ./mongodb_data:/data/db
    networks:
      - mern-network

volumes:
  mongodb_data: 